### ISSUE TITLE
make it citable

### ISSUE THREAD

**Issue by jcolomb** [delftopenhardware/openhardware.academy#16]
would be nice to have a citation here, putatively:
- use a CITATION.cff
- push to zenodo 
- both of the above

**Comment by jurra** [comment]
Hi @jcolomb sorry for the late reply, we overlooked this issue, as it is during this time where we prepare a new cohort.
Thanks for your suggestions.

We have archived the lessons of the previous cohorts. Each lesson with a DOI etc:
https://zenodo.org/communities/openhardware_academy/?page=1&size=20

(The lessons don't even exist in a github repo, they have been archived directly to zenodo, as the lessons are mostly developed in hackmd) 

This website's content is mostly operational and less off content itself like the lessons.
Would you also recommend making this repository citable?

I think the upload to zenodo is done via the lessons, but I dont see a clear need to archive in zenodo this website.
If you think it makes sense to do so it would be great to hear your thoughts about it.

Thanks again for opening the issue.

**Comment by jcolomb** [comment]
How you want to do this is your choice, but it would be nice to have one way to cite the whole course, adding a CITATION.cff file here would be a start, then maybe add a reference in the website ?

I personally use the zenodo-github integration to make it easier to be sure the latest content is on zenodo, but this means the github always has the latest version of the files, too.. .

**Comment by jurra** [comment]
Ok we will do that then, thanks again.

**Comment by jurra** [comment]
A note for us to make this citable. CITATION.cff doesnt apply to this case as it is not code. Instead is an educational resource.
For this the best option seems to be this one: https://www.dublincore.org/about/lrmi/

However is not that straigtforward as .cff, so lets see how we can do it.
Other options are standard citation formats.....

**Comment by jcolomb** [comment]
as long as I know, cff does not require it to be code, it is just a way to tell how to cite it. (the turing way is using .cff I think, I am using it for a website,...)
I have treated it like datasets

but digging in: https://github.com/citation-file-format/citation-file-format/issues/430

**Comment by jurra** [comment]
Hi@jcolomb sorry for the delay, I added some basic citation guides for the content. Maybe later we can add the lmri: https://www.dublincore.org/about/lrmi/
